// Generates the two things the design-sync converter can't discover on its own
// in this repo: a bundle entry barrel and the component→source map.
//
// Why they're generated rather than discovered: beide is an Electron app, not a
// published package. There is no `dist/`, no shipped `.d.ts` tree, and no
// `node_modules/beide`, so the converter's default discovery (PascalCase value
// exports in the shipped types) finds nothing. Passing `--entry` at this file's
// output makes the converter resolve PKG_DIR to the repo root; `componentSrcMap`
// then supplies the component list explicitly.
//
//   node .design-sync/gen-entry.mjs
//
// Writes  .design-sync/ds-entry.tsx        (bundle entry — re-exports every component module)
//         .design-sync/.cache/src-map.json (componentSrcMap fragment, merged into config.json by hand)
//
// Re-run after adding or removing components, then re-run the converter.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { relative, resolve } from 'node:path';
import { Project, Node, ts } from 'ts-morph';

const ROOT = resolve(import.meta.dirname, '..');
const OUT_ENTRY = resolve(ROOT, '.design-sync/ds-entry.tsx');
const OUT_MAP = resolve(ROOT, '.design-sync/.cache/src-map.json');

// Component modules live under src/components. Everything else in src/ is
// stores, i18n, lib helpers, or the app root — none of it is design-system API.
const GLOB = 'src/components/**/*.tsx';

// Files whose exports are app wiring, not design-system components.
const SKIP_FILES = [/\/tool-registry\./, /\/tool-renderer\./];

// PascalCase exports that aren't React components (icon record objects, type-ish
// constants, variant factories). Kept out of the component list; still re-exported
// by the barrel so composed components can use them.
const NOT_COMPONENTS = new Set(['Icons', 'ToolRegistry']);

// Name collisions between two real components. `export *` would silently drop
// the ambiguous name from the bundle, so the loser is re-exported under an alias
// and its module switches to explicit named re-exports.
// Keyed by "<repo-relative path>::<exported name>" → alias.
const RENAMES = {
  // The input bar's own lightweight positioned popover, distinct from the
  // base-ui Popover set in src/components/ui/popover.tsx.
  'src/components/agent-elements/input/popover.tsx::Popover': 'InputPopover',
};

const project = new Project({
  skipAddingFilesFromTsConfig: true,
  compilerOptions: { jsx: ts.JsxEmit.Preserve, allowJs: true, skipLibCheck: true },
});
project.addSourceFilesAtPaths(resolve(ROOT, GLOB));

const files = project
  .getSourceFiles()
  .filter((sf) => !SKIP_FILES.some((rx) => rx.test(sf.getFilePath())))
  .sort((a, b) => a.getFilePath().localeCompare(b.getFilePath()));

const owners = new Map(); // exported name → [file, …]  (collision detection)
const components = {}; // Name → repo-relative src path
const barrelFiles = [];

for (const sf of files) {
  const rel = relative(ROOT, sf.getFilePath()).replaceAll('\\', '/');
  const valueExports = [];
  for (const [name, decls] of sf.getExportedDeclarations()) {
    const real =
      name === 'default'
        ? decls.map((d) => d.getName?.()).find((n) => n && n !== 'default')
        : name;
    if (!real) continue;
    const isValue = decls.some(
      (d) =>
        Node.isVariableDeclaration(d) ||
        Node.isFunctionDeclaration(d) ||
        Node.isClassDeclaration(d),
    );
    if (!isValue) continue; // type-only export — nothing to bundle
    valueExports.push(real);
    const exposed = RENAMES[`${rel}::${real}`] ?? real;
    owners.set(exposed, [...(owners.get(exposed) ?? []), rel]);
    if (/^[A-Z][A-Za-z0-9]*$/.test(exposed) && !NOT_COMPONENTS.has(exposed)) {
      components[exposed] = rel;
    }
  }
  if (!valueExports.length) continue;
  const renamed = valueExports.some((n) => RENAMES[`${rel}::${n}`]);
  barrelFiles.push(
    renamed
      ? `export { ${valueExports
          .map((n) => {
            const alias = RENAMES[`${rel}::${n}`];
            return alias ? `${n} as ${alias}` : n;
          })
          .join(', ')} } from ${JSON.stringify('../' + rel)};`
      : `export * from ${JSON.stringify('../' + rel)};`,
  );
}

const collisions = [...owners].filter(([, fs]) => fs.length > 1);
for (const [name, fs] of collisions) {
  console.error(`[COLLISION] ${name} exported by ${fs.length}: ${fs.join(', ')}`);
}

const header = `// GENERATED by .design-sync/gen-entry.mjs — do not edit by hand.
// Bundle entry for the design-sync converter: re-exports every component module
// under src/components so esbuild can assign them all to window.Beide.
`;
writeFileSync(
  OUT_ENTRY,
  header + barrelFiles.join('\n') + '\n',
);

mkdirSync(resolve(ROOT, '.design-sync/.cache'), { recursive: true });
writeFileSync(
  OUT_MAP,
  JSON.stringify(Object.fromEntries(Object.entries(components).sort()), null, 2) + '\n',
);

console.error(
  `wrote ${barrelFiles.length} barrel re-exports, ${Object.keys(components).length} components` +
    (collisions.length ? `, ${collisions.length} COLLISIONS (fix before building)` : ''),
);
